apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/Khalid-faizan/helmcharts
    targetRevision: HEAD
    path: demo-chart
  destination:
    server : https://kubernetes.default.svc
    namespace: default
  

